services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    expose:
      - ${FRONTEND_PORT}
    networks:
      - auth-networks

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    networks:
      - auth-networks

networks:
  auth-networks:
    driver: bridge